alias exifinfo='exiftool -common'
alias exifclean='exiftool -P -overwrite_original -all= '
alias ls='ls -GFh'
alias ll='ls -alGFh'
alias python='python3'
alias rsamans='stoken --rcfile=$HOME/.stokenrc-mans'
alias rsacdw='stoken --rcfile=$HOME/.stokenrc-cdw'
alias venfix='source /usr/local/bin/virtualenvwrapper.sh'
alias hangups='hangups --col-scheme solarized-dark --col-palette-colors 256 --col-msg-sender-fg "light red"'
alias vaultauth='vault auth 3bbda1c1-d59c-5dbc-311f-a953ff3aa49d'
alias vaultunseal='~/vault/unseal.sh'
alias vaultstuff='vaultunseal && vaultauth'
alias mysql-util='mysql -h 127.0.0.1 -u root -p'
alias powerlineme='. /usr/local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh'
alias vpn='/opt/cisco/anyconnect/bin/vpn'
alias po='poetry'
alias ji='jira issue'
alias jisl='jira sprint list --current -a$(jira me)'
alias jim='jira issue list -a$(jira me) -s~Done -s~Cancelled'
alias jib='jira issue list -s~Done -s~Cancelled -q "sprint is empty and issuetype not in (Epic, Sub-task)" --order-by rank --reverse'
alias jic='jira issue create --template ~/.jira.tmpl -a 2344@services.cdw.com -tStory'
