alias exifinfo='exiftool -common'
alias exifclean='exiftool -P -overwrite_original -all= '
alias ls='ls -GFh'
alias ll='ls -lGFh'
alias python='python3'
alias rsacdw='stoken --rcfile=$HOME/.stokenrc-cdw'
alias venfix='source /usr/local/bin/virtualenvwrapper.sh'
alias hangups='hangups --col-scheme solarized-dark --col-palette-colors 256 --col-msg-sender-fg "light red"'
alias vaultauth='vault auth 3bbda1c1-d59c-5dbc-311f-a953ff3aa49d'
alias vaultunseal='~/vault/unseal.sh'
alias vaultstuff='vaultunseal && vaultauth'
alias mysql-util='mysql -h 127.0.0.1 -u root -p'